default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tomo178
  password: Amazarashi178
  host: realworld-db.cypojsfkdxhc.ap-northeast-1.rds.amazonaws.com


development:
  <<: *default
  database: realworld_development

test:
  <<: *default
  database: realworld_test

production:
  <<: *default
  database: realworld_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: realworld-db.cypojsfkdxhc.ap-northeast-1.rds.amazonaws.com